version: "3.3"

services:
  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "user"
      # You can use whatever password you like
      MYSQL_PASSWORD: "password"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - my-datavolume:/var/lib/mysql
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
  wordpress:
    container_name: wordpress-apache
    depends_on:
      - db
    image: wordpress:5.3-apache
    volumes:
      - .:/var/www/html # bind mounting current directory!
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: "user"
      WORDPRESS_DB_PASSWORD: "password"
      WORDPRESS_DB_NAME: "db"
volumes:
  my-datavolume:
