version: "3.3"

services:
  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - my-datavolume:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
  wordpress:
    container_name: wordpress-apache
    depends_on:
      - db
    image: wordpress:5.3-apache
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: "user"
      WORDPRESS_DB_PASSWORD: "password"
      WORDPRESS_DB_NAME: "db"
volumes:
  my-datavolume:
